services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mss
    ports:
      - "5432:5432"
    volumes:
      - mss_db:/var/lib/postgresql/data

volumes:
  mss_db:
